version: '3.7'

volumes:
    mongo_data: {}


services:
  prediction_service:
    build:
      context: prediction_service
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      MONGODB_ADDRESS: "mongodb://mongo.:27017/"
    ports:
      - "9696:9696"

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
